name: flutter_material_showcase
description: Material Design components showcase for Flutter apps. Use this package to check your ThemeData against most Material widgets.
version: 3.0.0
homepage: https://github.com/miquelbeltran/flutter_material_showcase
funding: https://github.com/sponsors/miquelbeltran

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.0.0

flutter:
